services:
  nextjs-dashboard:
    container_name: nextjs-dashboard
    build:
      context: ./nextjs-dashboard
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - "3000:3000"

  