services:
  nextjs-dashboard:
    container_name: nextjs-dashboard-dev
    build:
      context: ./nextjs-dashboard
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
      - "24678:24678"  # Drizzle Kit port
    networks:
      - my_network
  db:
    image: postgres:17.0
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postresql/data
    networks:
      - my_network
volumes:
    pgdata:


  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
